version: '3'
services:
  db:
    image: mongo:3.0.15
    ports:
      - "27017:27017"
  web:
    build:
      context: .
    command: gunicorn branching_cycle.main:app --workers=4 --bind 0.0.0.0:5000 --reload
    volumes:
      - .:/branching_cycle
    ports:
      - "5000:5000"
    depends_on:
      - db
